[package]
name = "risingwave_expr_impl"
description = "RisingWave function implementations."
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["chrono-tz", "futures-async-stream"]

[features]
external-udf = ["arrow-udf-flight", "tonic", "ginepro"]
js-udf = ["arrow-udf-js"]
python-udf = ["arrow-udf-python"]
wasm-udf = ["arrow-udf-wasm", "zstd"]

[dependencies]
aho-corasick = { workspace = true }
anyhow = { workspace = true }
arrow-udf-flight = { workspace = true, optional = true }
arrow-udf-js = { workspace = true, optional = true }
arrow-udf-python = { workspace = true, optional = true }
arrow-udf-wasm = { workspace = true, optional = true }
async-trait = { workspace = true }
auto_enums = { workspace = true }
bytes = { workspace = true }
# The feature setting is also used in src/expr/impl/src/udf/wasm.rs
chrono = { workspace = true, features = ["clock", "std"] }
chrono-tz = { workspace = true, features = ["case-insensitive"] }
constant_time_eq = { workspace = true }
educe = { workspace = true }
fancy-regex = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
futures-async-stream = { workspace = true }
futures-util = { workspace = true }
ginepro = { workspace = true, optional = true }
hex = { workspace = true }
hmac = { workspace = true }
iceberg = { workspace = true }
itertools = { workspace = true }
jsonbb = { workspace = true }
linkme = { workspace = true }
md5 = { workspace = true }
moka = { workspace = true, features = ["sync"] }
num-traits = { workspace = true }
openssl = { workspace = true }
regex = { workspace = true }
risingwave_common = { workspace = true }
risingwave_common_estimate_size = { workspace = true }
risingwave_expr = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_sqlparser = { workspace = true }
rust_decimal = { workspace = true, features = ["db-postgres", "maths"] }
self_cell = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
smallvec = { workspace = true }
sql-json-path = { workspace = true, features = ["jsonbb"] }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = ["time"] }
# For arrow-udf-flight
tonic = { version = "0.12", optional = true }
tracing = { workspace = true }
zstd = { workspace = true, optional = true }

[dev-dependencies]
criterion = { workspace = true }
expect-test = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "macros",
] }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[[bench]]
name = "expr"
harness = false

[lints]
workspace = true
