[package]
name = "with_options"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = { workspace = true }
syn = "2"

[lib]
proc-macro = true

[dev-dependencies]

[lints]
workspace = true
