[package]
name = "risingwave_frontend_macro"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { version = "2", features = ["full", "extra-traits"] }

[lib]
proc-macro = true
