[package]
name = "risingwave_meta"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
test = []
failpoints = ["fail/failpoints"]

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
assert_matches = { workspace = true }
async-trait = { workspace = true }
base64-url = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
chrono = { workspace = true }
clap = { workspace = true }
comfy-table = { workspace = true }
crepe = { workspace = true }
easy-ext = { workspace = true }
educe = { workspace = true }
either = { workspace = true }
enum-as-inner = { workspace = true }
fail = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
hex = { workspace = true }
http = { workspace = true }
itertools = { workspace = true }
jsonbb = { workspace = true }
maplit = { workspace = true }
notify = { workspace = true, features = ["macos_fsevent"] }
num-integer = { workspace = true }
num-traits = { workspace = true }
otlp-embedded = { workspace = true }
parking_lot = { workspace = true }
prometheus = { workspace = true }
prometheus-http-query = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
risingwave_backup = { workspace = true }
risingwave_common = { workspace = true }
risingwave_common_heap_profiling = { workspace = true }
risingwave_connector = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_license = { workspace = true }
risingwave_meta_dashboard = { workspace = true }
risingwave_meta_model = { workspace = true }
risingwave_meta_model_migration = { workspace = true }
risingwave_object_store = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
risingwave_sqlparser = { workspace = true }
rw_futures_util = { workspace = true }
scopeguard = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
sync-point = { workspace = true }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true, features = ["util", "load-shed"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
assert_matches = { workspace = true }
expect-test = { workspace = true }
rand = { workspace = true }
risingwave_hummock_sdk = { workspace = true, features = ["test"] }
risingwave_test_runner = { workspace = true }
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(not(madsim))'.dependencies]
axum = { workspace = true }
tower-http = { version = "0.6", features = [
    "add-extension",
    "cors",
    "fs",
    "compression-gzip",
] }
workspace-hack = { path = "../workspace-hack" }

[lints]
workspace = true
