[package]
name = "risingwave_common_estimate_size"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
bytes = { workspace = true }
educe = { workspace = true }
ethnum = { workspace = true, features = ["serde"] }
fixedbitset = { workspace = true }
jsonbb = { workspace = true }
risingwave_common_proc_macro = { workspace = true }
rust_decimal = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
