[package]
name = "risingwave_common_service"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true, features = ["query"] }
futures = { workspace = true, features = ["alloc"] }
http = { workspace = true }
prometheus = { workspace = true }
risingwave_common = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = ["rt", "rt-multi-thread", "sync", "macros", "time", "signal"] }
tonic = { workspace = true }
tower = { workspace = true, features = ["util", "load-shed"] }
tower-http = { workspace = true, features = ["add-extension", "compression-gzip"] }
tracing = { workspace = true }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[lints]
workspace = true
