[package]
name = "risingwave_common_proc_macro"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
proc-macro = true





[dependencies]
proc-macro-error = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
syn = "1"
bae = { workspace = true }
itertools = { workspace = true }

[lints]
workspace = true
