[package]
name = "risingwave_backup"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
itertools = { workspace = true }
parking_lot = { workspace = true }
prost = { workspace = true }
risingwave_common = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_meta_model = { workspace = true }
risingwave_object_store = { workspace = true }
risingwave_pb = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
twox-hash = { workspace = true }

[dev-dependencies]
risingwave_hummock_sdk = { workspace = true }

[lints]
workspace = true
