[package]
name = "risingwave_pb"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
enum-as-inner = { workspace = true }
pbjson = { workspace = true }
prost = { workspace = true }
prost-helpers = { workspace = true }
risingwave_error = { workspace = true }
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
fs-err = { workspace = true }
pbjson-build = { workspace = true }
prost-build = { workspace = true }
tonic-build = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
static_assertions = { workspace = true }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[lints]
workspace = true
