[package]
name = "rw_futures_util"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
futures = { workspace = true }
pin-project-lite = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[lints]
workspace = true
