[package]
name = "sync-point"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = { workspace = true }
spin = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = ["sync", "time"] }

[features]
sync_point = []

[lints]
workspace = true
