[package]
name = "risingwave_common_secret"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }


[dependencies]
aws-lc-rs = { workspace = true, features = ["aws-lc-sys"] }
anyhow = { workspace = true }
bincode = "1"
parking_lot = { workspace = true }
prost = { workspace = true }
risingwave_pb = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
hex = { workspace = true }

[lints]
workspace = true
