[package]
name = "risingwave_sqlparser"
license = "Apache-2.0"
include = ["src/**/*.rs", "Cargo.toml"]
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }

[package.metadata.release]
# Instruct `cargo release` to not run `cargo publish` locally:
# https://github.com/sunng87/cargo-release/blob/master/docs/reference.md#config-fields
# See docs/releasing.md for details.
disable-publish = true

[features]
default = ["std"]
std = []

[dependencies]
itertools = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
thiserror = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "macros",
] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
winnow = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
console = { workspace = true }
libtest-mimic = { workspace = true }
matches = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
serde_yaml = { workspace = true }
walkdir = { workspace = true }

[lib]
path = "src/lib.rs"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[[bin]]
name = "sqlparser"
path = "src/bin/sqlparser.rs"

[[test]]
name = "parser_test"
harness = false

[lints]
workspace = true
