[package]
name = "risingwave_expr"
description = "Core expression traits and function registry."
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
auto_impl = { workspace = true }
await-tree = { workspace = true }
chrono = { workspace = true, features = ["clock", "std"] }
const-currying = { workspace = true }
downcast-rs = { workspace = true }
easy-ext = { workspace = true }
educe = { workspace = true }
either = { workspace = true }
enum-as-inner = { workspace = true }
futures = { workspace = true }
futures-async-stream = { workspace = true }
futures-util = { workspace = true }
itertools = { workspace = true }
linkme = { workspace = true }
num-traits = { workspace = true }
parse-display = { workspace = true }
paste = { workspace = true }
prometheus = { workspace = true }
risingwave_common = { workspace = true }
risingwave_common_estimate_size = { workspace = true }
risingwave_expr_macro = { workspace = true }
risingwave_pb = { workspace = true }
smallvec = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt-multi-thread",
    "macros",
] }
tracing = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[lints]
workspace = true
