[package]
name = "risingwave_java_binding"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
cfg-or-panic = { workspace = true }
foyer = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
jni = { workspace = true }
prost = { workspace = true }
risingwave_common = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_jni_core = { workspace = true }
risingwave_object_store = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_storage = { workspace = true }
rw_futures_util = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "fs",
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tracing = { workspace = true }

[dev-dependencies]
risingwave_expr = { workspace = true }

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "data-chunk-payload-generator"
test = false
bench = false

[[bin]]
name = "data-chunk-payload-convert-generator"
test = false
bench = false

[lints]
workspace = true
