[package]
name = "risingwave_common_metrics"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
auto_impl = { workspace = true }
bytes = { workspace = true }
cfg-or-panic = { workspace = true }
clap = { workspace = true }
easy-ext = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
http = { workspace = true }
http-02 = { workspace = true }
hyper = { version = "1" }
hyper-014 = { package = "hyper", version = "0.14", features = ["client"] }
hyper-util = { workspace = true, features = ["client-legacy"] }
hytra = { workspace = true }
itertools = { workspace = true }
parking_lot = { workspace = true }
pin-project-lite = { workspace = true }
prometheus = { workspace = true }
rw_iter_util = { workspace = true }
rw_resource_util = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio" }
tonic = { workspace = true }
tower-layer = { workspace = true }
tower-service = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(not(madsim))'.dependencies]
http-body = "1"
[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.17", default-features = false }
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
darwin-libproc = { git = "https://github.com/risingwavelabs/darwin-libproc.git", rev = "a502be24bd0971463f5bcbfe035a248d8ba503b7" }
libc = "0.2"
mach2 = "0.4"

[lints]
workspace = true
