[package]
name = "rw_resource_util"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
fs-err = { workspace = true }
sysinfo = { workspace = true, features = ["system"] }
thiserror-ext = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
