[package]
name = "risingwave_dml"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
futures = { workspace = true, features = ["alloc"] }
futures-async-stream = { workspace = true }
itertools = { workspace = true }
parking_lot = { workspace = true }
risingwave_common = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tracing = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
paste = { workspace = true }
tempfile = { workspace = true }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[lints]
workspace = true
