[package]
name = "risingwave_frontend"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
auto_enums = { workspace = true }
auto_impl = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
bk-tree = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
downcast-rs = { workspace = true }
dyn-clone = { workspace = true }
easy-ext = { workspace = true }
educe = { workspace = true }
either = { workspace = true }
enum-as-inner = { workspace = true }
fancy-regex = { workspace = true }
fixedbitset = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
futures-async-stream = { workspace = true }
iana-time-zone = { workspace = true }
iceberg = { workspace = true }
itertools = { workspace = true }
jsonbb = { workspace = true }
linkme = { workspace = true }
maplit = { workspace = true }
md5 = { workspace = true }
memcomparable = { workspace = true }
mysql_async = { workspace = true, features = ["default"] }
num-integer = { workspace = true }
parking_lot = { workspace = true }
parse-display = { workspace = true }
paste = { workspace = true }
petgraph = { workspace = true }
pgwire = { workspace = true }
pin-project-lite = { workspace = true }
postgres-types = { workspace = true }
pretty-xmlish = { workspace = true }
pretty_assertions = { workspace = true }
prometheus = { workspace = true, features = ["process"] }
prost = { workspace = true }
quick-xml = { workspace = true, features = ["serialize"] }
rand = { workspace = true, features = ["small_rng"] }
risingwave_batch = { workspace = true }
risingwave_common = { workspace = true }
risingwave_common_heap_profiling = { workspace = true }
risingwave_common_service = { workspace = true }
risingwave_connector = { workspace = true }
risingwave_dml = { workspace = true }
risingwave_expr = { workspace = true }
risingwave_frontend_macro = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
risingwave_sqlparser = { workspace = true }
risingwave_storage = { workspace = true }
risingwave_variables = { workspace = true }
rw_futures_util = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
smallvec = { workspace = true, features = ["serde"] }
speedate = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tokio-postgres = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true, features = ["util", "load-shed"] }
tower-http = { workspace = true, features = ["add-extension", "cors", "compression-gzip"] }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
expect-test = { workspace = true }
risingwave_batch_executors = { workspace = true }
risingwave_expr_impl = { workspace = true }
tempfile = { workspace = true }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[lints]
workspace = true
