[package]
name = "risingwave_hummock_test"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
failpoints = ["risingwave_storage/failpoints"]
sync_point = ["sync-point/sync_point", "serial_test"]
test = []

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
fail = { workspace = true }
foyer = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
futures-async-stream = { workspace = true }
itertools = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
risingwave_common = { workspace = true }
risingwave_common_service = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_hummock_trace = { workspace = true }
risingwave_meta = { workspace = true, features = ["test"] }
risingwave_object_store = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
risingwave_storage = { workspace = true, features = ["test"] }
serial_test = { workspace = true, optional = true }
tokio = { version = "0.2", package = "madsim-tokio" }

[dev-dependencies]
criterion = { workspace = true, features = ["async_futures"] }
expect-test = { workspace = true }
futures = { workspace = true, features = ["alloc", "executor"] }

futures-async-stream = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_test_runner = { workspace = true }
sync-point = { workspace = true }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[[bench]]
name = "bench_hummock_iter"
harness = false
required-features = ["test"]

[[bin]]
name = "replay"
path = "src/bin/replay/main.rs"

[lints]
workspace = true
