[package]
name = "risedev-config"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
clap = { workspace = true }
console = { workspace = true }
dialoguer = { workspace = true }
enum-iterator = { workspace = true }
fs-err = { workspace = true }
itertools = { workspace = true }

[lints]
workspace = true
