[package]
name = "pgwire"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
auto_enums = { workspace = true }
byteorder = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
itertools = { workspace = true }
jsonwebtoken = { workspace = true }
openssl = { workspace = true }
panic-message = { workspace = true }
parking_lot = { workspace = true }
peekable = { workspace = true, features = ["tokio"] }
postgres-types = { workspace = true }
reqwest = { workspace = true }
risingwave_common = { workspace = true }
risingwave_sqlparser = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
socket2 = { workspace = true }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "macros",
] }
tokio-openssl = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio-postgres = { workspace = true }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[lints]
workspace = true
