[package]
name = "risingwave_connector_codec"
description = "Encoding and decoding between external data formats and RisingWave datum"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
apache-avro = { workspace = true }
chrono = { workspace = true, features = ["clock", "std"] }
easy-ext = { workspace = true }
itertools = { workspace = true }
jsonbb = { workspace = true }
jst = { package = 'jsonschema-transpiler', git = "https://github.com/mozilla/jsonschema-transpiler", rev = "c1a89d720d118843d8bcca51084deb0ed223e4b4" }
num-bigint = { workspace = true }
prost = { workspace = true, features = ["no-recursion-limit"] }
prost-reflect = { workspace = true, features = ["serde"] }
prost-types = { workspace = true }
protox = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
risingwave_common = { workspace = true }
risingwave_pb = { workspace = true }
rust_decimal = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
fs-err = { workspace = true }
hex = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio" }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[lints]
workspace = true
