[package]
name = "prost-helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = "2"

[lib]
proc-macro = true

[lints]
workspace = true
