[package]
name = "risingwave_hummock_trace"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
bincode = { version = "=2.0.0-rc.3", features = ["serde"] }
byteorder = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
futures = { workspace = true, features = ["alloc"] }
futures-async-stream = { workspace = true }
parking_lot = { workspace = true }
prost = { workspace = true }
risingwave_common = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_pb = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio" }
tracing = { workspace = true }
foyer = { workspace = true }

[dev-dependencies]
itertools = { workspace = true }
mockall = { workspace = true }
risingwave_hummock_sdk = { workspace = true }

[lints]
workspace = true
