[package]
name = "risingwave_hummock_sdk"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
test = []

[dependencies]
bytes = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
parse-display = { workspace = true }
risingwave_common = { workspace = true }
risingwave_common_estimate_size = { workspace = true }
risingwave_pb = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[lints]
workspace = true
