[package]
name = "risedev"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
chrono = { workspace = true, features = ["clock", "std"] }
clap = { workspace = true }
console = { workspace = true }
fs-err = { workspace = true }
glob = { workspace = true }
google-cloud-pubsub = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
panic-message = { workspace = true }
rdkafka = { workspace = true }
redis = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
serde_yaml = { workspace = true }
sqlx = { workspace = true, features = ["any"] }
tempfile = { workspace = true }
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url = { workspace = true }
workspace-hack = { workspace = true }
yaml-rust = { workspace = true }

[lints]
workspace = true
