[package]
name = "risingwave_storage"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
# rocksdb-local = ["rocksdb"]
# tikv = ["tikv-client"]
test = ["risingwave_hummock_sdk/test"]
failpoints = ["fail/failpoints"]
hm-trace = []

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
async-trait = { workspace = true }
auto_enums = { workspace = true }
await-tree = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
dyn-clone = { workspace = true }
either = { workspace = true }
enum-as-inner = { workspace = true }
fail = { workspace = true }
foyer = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
futures-async-stream = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
lz4 = { workspace = true }
memcomparable = { workspace = true }
mixtrics = { workspace = true }
moka = { workspace = true, features = ["future", "sync"] }
more-asserts = { workspace = true }
num-integer = { workspace = true }
parking_lot = { workspace = true }
prometheus = { workspace = true, features = ["process"] }
prost = { workspace = true }
rand = { workspace = true }
risingwave_backup = { workspace = true }
risingwave_common = { workspace = true }
risingwave_common_estimate_size = { workspace = true }
risingwave_common_service = { workspace = true }
risingwave_expr = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_hummock_trace = { workspace = true }
risingwave_object_store = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
scopeguard = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_bytes = { workspace = true }
sled = { workspace = true }
spin = { workspace = true }
sync-point = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
# tikv-client = { git = "https://github.com/tikv/client-rust", rev = "5714b2", optional = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "fs",
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
xorf = { workspace = true }
xxhash-rust = { workspace = true, features = ["xxh32", "xxh64"] }
zstd = { workspace = true }

[dev-dependencies]
bincode = "1"
criterion = { workspace = true, features = ["async_futures", "async_tokio"] }
expect-test = { workspace = true }
risingwave_hummock_sdk = { workspace = true, features = ["test"] }
risingwave_test_runner = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.17", default-features = false }
libc = "0.2"
nix = { version = "0.29", features = ["fs", "mman"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
fiemap = "0.1.1"

[target.'cfg(target_os = "macos")'.dependencies]
darwin-libproc = { git = "https://github.com/risingwavelabs/darwin-libproc.git", rev = "a502be24bd0971463f5bcbfe035a248d8ba503b7" }
libc = "0.2.148"
mach2 = "0.4"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[[bench]]
name = "bench_block_iter"
harness = false
# Enable debug if you want to generate flamegraph.
# debug = true

[[bench]]
name = "bench_block_cache"
harness = false

[[bench]]
name = "bench_merge_iter"
harness = false

[[bench]]
name = "bench_fs_operation"
harness = false

[[bench]]
name = "bench_compression"
harness = false

[[bench]]
name = "bench_compactor"
harness = false

[[bench]]
name = "bench_multi_builder"
harness = false

[[bench]]
name = "bench_row"
harness = false

[[bench]]
name = "bench_imm_compact"
harness = false

[[bench]]
name = "bench_table_watermarks"
harness = false

[lints]
workspace = true
