[package]
name = "risingwave_rpc_client"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
easy-ext = { workspace = true }
either = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
http = { workspace = true }
lru = { workspace = true }
moka = { workspace = true, features = ["future"] }
paste = { workspace = true }
rand = { workspace = true }
risingwave_common = { workspace = true }
risingwave_error = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_pb = { workspace = true }
rw_futures_util = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
risingwave_hummock_sdk = { workspace = true }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[lints]
workspace = true
