[package]
name = "risingwave-fields-derive"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { version = "2", features = ["full", "extra-traits"] }

[dev-dependencies]
expect-test = { workspace = true }
indoc = { workspace = true }
prettyplease = { workspace = true, features = ["verbatim"] }

[lib]
proc-macro = true
