[package]
name = "risingwave_error"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bincode = "1"
easy-ext = { workspace = true }
serde = { workspace = true }
serde-error = { workspace = true }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
