---
version: "3"
services:
  risingwave-standalone:
    extends:
      file: ../../docker/docker-compose-with-sqlite.yml
      service: risingwave-standalone
  grafana-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: grafana-0
  minio-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: minio-0
  prometheus-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: prometheus-0
  mongodb:
    extends:
      file: ../mongodb/docker-compose.yaml
      service: mongodb
  mongodb-setup:
    extends:
      file: ../mongodb/docker-compose.yaml
      service: mongodb-setup
  random_data_generator:
    extends:
      file: ../mongodb/docker-compose.yaml
      service: random_data_generator

volumes:
  risingwave-standalone:
    external: false
  grafana-0:
    external: false
  minio-0:
    external: false
  prometheus-0:
    external: false
name: risingwave-compose
