[package]
name = "risingwave_expr_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { version = "2", features = ["full", "extra-traits"] }

[lib]
proc-macro = true

[lints]
workspace = true
