name: Update Helm Charts and Risingwave Operator on New Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'release version'
        required: true

env:
  NEW_APP_VERSION: ${{ github.event.inputs.version || github.event.release.tag_name }}

jobs:
  update-helm-charts:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Helm Charts Repository
        uses: actions/checkout@v4
        with:
          repository: 'risingwavelabs/helm-charts'
          token: ${{ secrets.PR_TOKEN }}
          path: 'helm-charts'

      - name: Create a new branch
        run: |
          cd helm-charts
          git checkout -b auto-update-${{ env.NEW_APP_VERSION }}
          git push --set-upstream origin auto-update-${{ env.NEW_APP_VERSION }}
