name: Update Helm Charts and Risingwave Operator on New Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'release version'
        required: true

env:
  NEW_APP_VERSION: ${{ github.event.inputs.version || github.event.release.tag_name }}

jobs:
  update-helm-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Helm Charts Repository
        uses: actions/checkout@v3
        with:
          repository: 'risingwavelabs/helm-charts'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'helm-charts'

      - name: Create a new branch
        run: |
          cd helm-charts
          git checkout -b 'auto-update-${{ env.NEW_APP_VERSION }}'

      - name: Update values.yaml
        run: |
          sed -i "s/^  tag:.*/  tag: \"${{ env.NEW_APP_VERSION }}\"/" helm-charts/charts/risingwave/values.yaml

      - name: Update Chart.yaml
        run: |
          cd helm-charts/charts/risingwave
          CURRENT_VERSION=$(grep 'version:' Chart.yaml | awk '{print $2}' | head -n 1)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS='.' '{$NF++; print}')
          sed -i "/type: application/,/version:/!b; /version:/s/version: .*/version: $NEW_VERSION/" Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"${{ env.NEW_APP_VERSION }}\"/" Chart.yaml
          echo "NEW_CHART_VERSION=$NEW_VERSION" >> $GITHUB_ENV

       - name: Commit changes
        run: |
          cd helm-charts
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: bump risingwave to ${{ env.NEW_APP_VERSION }}, release chart ${{ env.NEW_CHART_VERSION }}"

      - name: Push new branch
        run: |
          cd helm-charts
          git push --set-upstream origin 'auto-update-${{ env.NEW_APP_VERSION }}'

      - name: Create Pull Request
        uses: repo-sync/pull-request@v3
        with:
          source_branch: 'auto-update-${{ env.NEW_APP_VERSION }}'
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          pr_title: "chore: bump risingwave to ${{ env.NEW_APP_VERSION }}, release chart ${{ env.NEW_CHART_VERSION }}"
          pr_body: "This is an automated pull request to update the chart versions."
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: 'chore: bump risingwave to ${{ env.NEW_APP_VERSION }}, release chart ${{ env.NEW_CHART_VERSION }}'
      #     committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      #     author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
      #     title: 'chore: bump risingwave to ${{ env.NEW_APP_VERSION }}, release chart ${{ env.NEW_CHART_VERSION }}'
      #     body: 'This is an automated pull request to update the chart versions'
      #     branch: 'auto-update-${{ env.NEW_APP_VERSION }}'
      #     path: 'helm-charts'

  update-risingwave-operator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Risingwave Operator Repository
        uses: actions/checkout@v3
        with:
          repository: 'risingwavelabs/risingwave-operator'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'risingwave-operator'

      - name: Update risingwave-operator image tags
        run: |
          cd risingwave-operator
          PREV_VERSION=$(grep -roh "risingwavelabs/risingwave:v[0-9\.]*" * | head -n 1 | cut -d':' -f2)
          grep -rl "risingwavelabs/risingwave:$PREV_VERSION" . | xargs sed -i "s|risingwavelabs/risingwave:$PREV_VERSION|risingwavelabs/risingwave:${{ env.NEW_APP_VERSION }}|g"

      - name: Create Pull Request for risingwave-operator
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: bump risingwave image tags to ${{ env.NEW_APP_VERSION }}'
          title: 'chore: bump risingwave image tags to ${{ env.NEW_APP_VERSION }}'
          body: 'This is an automated pull request to update the risingwave image tags'
          branch: 'auto-update-${{ env.NEW_APP_VERSION }}'
          path: 'risingwave-operator'
